# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a70614d4ba2c1ede7c8df7ff698bf40d"
name = "tracking-app-php"
handle = "tracking-app-php"
application_url = "https://fought-attorneys-mutual-largest.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ipoc-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://fought-attorneys-mutual-largest.trycloudflare.com/auth/callback",
  "https://fought-attorneys-mutual-largest.trycloudflare.com/auth/shopify/callback",
  "https://fought-attorneys-mutual-largest.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
